[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
rj_core = { path = "crates/rj_core" }

[workspace.package]
authors = ["1gy"]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/1gy/rj"
